<h1>Se connecter</h1>
<form class="login-form" action="login.php" method="post">
  <p>
    <label for="email">email</label>
    <input type="email" id="email" name="email" placeholder="email" required>
  </p>
  <p>
    <label for="password">Mot de Passe</label>
    <input type="password" id="password" name="password" placeholder="password" required>
  </p>
  <button type="submit" class="button">S'identifier</button>
</form>