<h1>Ajouter une catégorie</h1>

<!-- Section #author-edit : section d'édition/ajout d'un auteur -->
<section id="author-edit"> <!-- JE ne change pas le nom de la section, car je veux le même design ! -->
  <hr>
  <form action="add_category.php" method="post">
    <p>
      <label for="categoryName">Nom de la catégorie</label>
      <input type="text" name="categoryName" id="categoryName" placeholder="Nom de la catégorie" required autofocus>
    </p>

    <button type="submit" class="button">Ajouter</button>
  </form>
</section>