<h1>Ajouter un auteur</h1>

<!-- Section #author-edit : section d'édition/ajout d'un auteur -->
<section id="author-edit">
  <hr>
  <form action="add_author.php" method="post">
    <p>
      <label for="firstName">Prénom</label>
      <input type="text" name="firstName" id="firstName" placeholder="Prénom" required  autofocus>
    </p>
    <p>
      <label for="lastName">Nom</label>
      <input type="text" name="lastName" id="lastName" placeholder="Nom" required>
    </p>
    <button type="submit" class="button">Ajouter</button>
  </form>
</section>