<h1>Liste des commentaires</h1>
<!-- Section #author-list : Affiche la liste des auteurs -->
<section id="author-list">
  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>Pseudo</th>
        <th>Extrait du contenu</th>
        <th>Date</th>
        <th>Article du com.</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($comments as $comment): ?>
        <tr>
          <td><?= $comment['id']; ?></td>
          <td><?= $comment['nickname']; ?></td>
          <td><?= mb_strimwidth($comment['content'], 0, 60, ' (...)'); ?></td>
          <td><?= date("d/m/Y \à G:i", strtotime($comment['publicationDate'])); ?></td>
          <td><?= $comment['postTitle']; ?></td>
          <td>
            <a href="edit_comment.php?id=<?= $comment['id'] ?>"><i class="fas fa-edit"></i></a>
            <a href="delete_comment.php?id=<?= $comment['id'] ?>"><i class="fas fa-trash"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

</section>

