<h1>Editer une catégorie</h1>

<!-- Section #author-edit : section d'édition/ajout d'un auteur -->
<section id="author-edit"> <!-- Je ne change pas le nom, car je veux garder le même design ! -->
  <hr>
  <form action="edit_category.php" method="post">
    <p>
      <label for="categoryName">Nom de la catégorie</label>
      <input type="text" name="categoryName" id="categoryName" placeholder="Nom de la catégorie" required  autofocus value="<?= $category['name']; ?>">
    </p>

    <input type="hidden" name="id" value="<?= $category['id'] ?>">
    <button type="submit" class="button">Mettre à jour</button>
  </form>
</section>