<h1>Editer un auteur</h1>

<!-- Section #author-edit : section d'édition/ajout d'un auteur -->
<section id="author-edit">
  <hr>
  <form action="edit_author.php" method="post">
    <p>
      <label for="firstName">Prénom</label>
      <input type="text" name="firstName" id="firstName" placeholder="Prénom" required  autofocus value="<?= $author['firstName']; ?>">
    </p>
    <p>
      <label for="lastName">Nom</label>
      <input type="text" name="lastName" id="lastName" placeholder="Nom" required value="<?= $author['lastName']; ?>">
    </p>
    <input type="hidden" name="id" value="<?= $author['id'] ?>">
    <button type="submit" class="button">Mettre à jour</button>
  </form>
</section>