<h1>Liste des articles</h1>
<!-- Section #author-list : Affiche la liste des auteurs -->
<section id="author-list">
  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>Titre</th>
        <th>Date de publication</th>
        <th>Auteur</th>
        <th>Catégorie</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($posts as $post): ?>
        <tr>
          <td><?= $post['id']; ?></td>
          <td><?= $post['title']; ?></td>
          <td><?= date("d/m/Y \à G:i", strtotime($post['publicationDate'])); ?></td>
          <td><?= $post['authorFirstName']; ?> <?= $post['authorLastName']; ?></td>
          <td><?= $post['categoryName']; ?></td>
          <td>
            <a href="edit_post.php?id=<?= $post['id'] ?>"><i class="fas fa-edit"></i></a>
            <a href="delete_post.php?id=<?= $post['id'] ?>"><i class="fas fa-trash"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  <a href="add_post.php" class="button">Poster un nouvel article</a>
</section>